# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Be strict when checking our package
warnings_are_errors: false

install:
  - Rscript -e 'install.packages(c("roxygen2", "stringr", "knitr"))'
  # install 1.13.6 version of devtools, because the latest 2.0.0 version doesn't work
  - Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/devtools/devtools_1.13.6.tar.gz", repos=NULL, type="source")'
  - Rscript -e 'devtools::install_bioc(c("BiocInstaller", "rhdf5"))'

script:
  - Rscript -e 'devtools::install_deps(".")'
  - Rscript -e 'devtools::check(".")'
  - R CMD INSTALL .
  - Rscript tests/scripts/test.R
